/**
 * Consolidated Cloudflare Worker for Dynamic OG Meta Tags
 *
 * Handles all routes that need OG injection:
 *   /u/:username       — User profiles (dynamic, fetched from Xano)
 *   /index/:slug       — Articles (dynamic, fetched from Xano)
 *   /groups/:slug      — Groups (dynamic, fetched from Xano)
 *   /focus-groups      — Focus groups landing (static)
 */

import { ImageResponse } from 'workers-og';

const XANO_API_BASE = 'https://cloud.atlantium.ai/api:-ulnKZsX';
const APP_API_BASE = 'https://cloud.atlantium.ai/api:_c66cUCc';
const ATLANTIUM_API_BASE = 'https://api.atlantium.ai/v1';
const SITE_ORIGIN = 'https://atlantium.ai';

const BOT_USER_AGENTS =
  /facebookexternalhit|facebookcatalog|Facebot|FBAN|FBAV|FB_IAB|Messenger|Twitterbot|LinkedInBot|WhatsApp|Slackbot|Slack-ImgProxy|TelegramBot|Discordbot|Pinterest|Googlebot|bingbot|Applebot|redditbot|SkypeUriPreview|vkShare|Iframely|embedly|Yahoo|DuckDuckBot|Mastodon|Bluesky|nostr/i;

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const { pathname } = url;

    // Match routes
    let match;

    if ((match = pathname.match(/^\/u\/([^/]+)\/?$/))) {
      return handleOgRoute(request, () => fetchProfileOg(match[1]));
    }

    if ((match = pathname.match(/^\/index\/([^/]+)\/?$/))) {
      return handleOgRoute(request, () => fetchArticleOg(match[1]));
    }

    if ((match = pathname.match(/^\/groups\/([^/]+)\/?$/))) {
      return handleOgRoute(request, () => fetchGroupOg(match[1]));
    }

    if (pathname === '/focus-groups' || pathname === '/focus-groups/') {
      return handleOgRoute(request, () => staticFocusGroupsOg());
    }

    // Hub pages — the links a content launch actually shares. Without these
    // they unfurl as the generic site card.
    if (pathname === '/jobs' || pathname === '/jobs/') {
      return handleOgRoute(request, () => staticHubOg({
        title: 'Realtime ATL Tech Job Index | Atlantium',
        description:
          "Every Atlanta tech role, updated every 4 hours — live salary distribution, verified apply links, and no-degree signals. Atlantium: Atlanta's Technology Network.",
        path: '/jobs',
        // Rendered live so the role count is never stale (static PNG froze at
        // a number that aged out within days).
        image: `og/jobs-index.png?v=${OG_RENDER_VERSION}`,
      }));
    }

    if (pathname === '/directory' || pathname === '/directory/' || pathname === '/grants' || pathname === '/grants/') {
      return handleOgRoute(request, () => staticHubOg({
        title: 'The Working Map of Atlanta Tech | Atlantium',
        description:
          'Every investor writing checks in the Southeast, every accelerator and grant, 1,000+ companies hiring — profiled, checked continuously, free to browse.',
        path: '/directory',
      }));
    }

    if (pathname === '/training' || pathname === '/training/') {
      return handleOgRoute(request, () => staticHubOg({
        title: 'AI Engineering Intensive — 8 Weeks, Atlanta | Atlantium',
        description:
          'From where you are to shipping production AI: live sessions, a real client build, warm introductions to hiring partners. 30 seats a cohort — Atlanta Builder Grants cover up to half.',
        path: '/training',
      }));
    }

    if ((match = pathname.match(/^\/jobs\/([^/]+)\/?$/))) {
      return handleOgRoute(request, () => fetchJobOg(match[1]));
    }

    if (pathname === '/og/cover.png' || pathname === '/og/cover') {
      return renderCarouselCover(request);
    }

    if ((match = pathname.match(/^\/og\/social\/([^/]+?)(?:\.png)?\/?$/))) {
      return renderSocialJobCard(match[1], request);
    }

    if (pathname === '/og/jobs-index.png' || pathname === '/og/jobs-index') {
      return renderJobsIndexOgImage(request);
    }

    if ((match = pathname.match(/^\/og\/jobs\/([^/]+?)(?:\.png)?\/?$/))) {
      return renderJobOgImage(match[1], request);
    }

    if ((match = pathname.match(/^\/og\/directory\/([a-z]+)\/([^/]+?)(?:\.png)?\/?$/))) {
      return renderDirectoryOgImage(match[1], match[2], request);
    }

    if ((match = pathname.match(/^\/blog\/([^/]+)\/?$/))) {
      return handleOgRoute(request, () => fetchContentOg('post', match[1]));
    }

    if ((match = pathname.match(/^\/docs\/([^/]+)\/?$/))) {
      return handleOgRoute(request, () => fetchContentOg('doc', match[1]));
    }

    // Sitemap: generated by the API worker from published content, served on
    // the site origin so crawlers discover it at atlantium.ai/sitemap.xml.
    if ((match = pathname.match(/^\/directory\/([a-z]+)\/([^/]+)\/?$/))) {
      return handleOgRoute(request, () => fetchDirectoryOg(match[1], match[2]));
    }

    if (pathname === '/sitemap.xml') {
      return fetch(`${ATLANTIUM_API_BASE}/content/sitemap.xml`);
    }

    // All other requests — pass through
    return fetch(request);
  },
};

// ---------------------------------------------------------------------------
// Shared handler — bot detection, fetch origin, inject tags
// ---------------------------------------------------------------------------

async function handleOgRoute(request, getOgTags) {
  const userAgent = request.headers.get('user-agent') || '';
  const isBot = BOT_USER_AGENTS.test(userAgent);

  const originalResponse = await fetch(request);

  const contentType = originalResponse.headers.get('content-type') || '';
  if (!isBot || !contentType.includes('text/html')) {
    return originalResponse;
  }

  let html = await originalResponse.text();

  try {
    const ogTags = await getOgTags();
    if (ogTags) {
      html = injectOgTags(html, ogTags);
    }
  } catch (error) {
    console.error('OG tag injection error:', error);
  }

  return new Response(html, {
    status: originalResponse.status,
    headers: {
      ...Object.fromEntries(originalResponse.headers),
      'content-type': 'text/html;charset=UTF-8',
    },
  });
}

// ---------------------------------------------------------------------------
// Route handlers
// ---------------------------------------------------------------------------

async function fetchProfileOg(username) {
  const res = await fetch(
    `${XANO_API_BASE}/profile?username=${encodeURIComponent(username)}`
  );
  if (!res.ok) return null;

  const { profile, og } = await res.json();
  if (!profile || !og) return null;

  return buildOgString({
    type: og.type,
    siteName: og.site_name,
    title: og.title,
    description: og.description,
    image: og.image,
    url: og.url,
    twitterCard: 'summary',
  });
}

async function fetchArticleOg(slug) {
  const res = await fetch(
    `${XANO_API_BASE}/article?slug=${encodeURIComponent(slug)}`
  );
  if (!res.ok) return null;

  const { article, og } = await res.json();
  if (!article || !og) return null;

  const publishedTime = og.published_time
    ? new Date(og.published_time).toISOString()
    : '';

  const tagMetas = (og.tags || [])
    .map((t) => `<meta property="article:tag" content="${escapeHtml(t)}" />`)
    .join('\n    ');

  return buildOgString({
    type: og.type,
    siteName: og.site_name,
    title: og.title,
    description: og.description,
    image: og.image,
    url: og.url,
    twitterCard: 'summary_large_image',
    extra: `
    <meta property="article:author" content="${escapeHtml(og.author)}" />
    <meta property="article:published_time" content="${escapeHtml(publishedTime)}" />
    ${tagMetas}`,
  });
}

async function fetchGroupOg(slug) {
  const res = await fetch(
    `${XANO_API_BASE}/group?slug=${encodeURIComponent(slug)}`
  );
  if (!res.ok) return null;

  const { group, og } = await res.json();
  if (!group || !og) return null;

  return buildOgString({
    type: og.type,
    siteName: og.site_name,
    title: og.title,
    description: og.description,
    image: og.image,
    imageWidth: '1200',
    imageHeight: '630',
    url: og.url,
    twitterCard: 'summary_large_image',
  });
}

async function fetchJobOg(slug) {
  // Job postings live on the Neon-backed api worker (Xano og endpoint is dead).
  const res = await fetch(
    `${ATLANTIUM_API_BASE}/job_postings/${encodeURIComponent(slug)}`
  );
  if (!res.ok) return null;

  const job = await res.json();
  if (!job || !job.title) return null;

  const salary =
    job.salary_min && job.salary_max
      ? `$${Math.round(job.salary_min / 1000)}k–$${Math.round(job.salary_max / 1000)}k`
      : null;
  const parts = [
    job.workplace_type,
    job.location,
    salary,
    job.content && job.content.requirements_summary,
  ].filter(Boolean);
  const description = parts.join(' · ').slice(0, 250) ||
    `${job.title} at ${job.company} — AI & tech jobs in Atlanta on Atlantium.`;

  return buildOgString({
    type: 'website',
    siteName: 'Atlantium',
    title: `${job.title} at ${job.company} — Atlanta Tech Jobs`,
    description,
    // Version in the URL: unfurl caches key on the image URL, so bumping
    // OG_RENDER_VERSION makes platforms fetch the new render.
    image: `${SITE_ORIGIN}/og/jobs/${encodeURIComponent(slug)}.png?v=${OG_RENDER_VERSION}`,
    imageWidth: '1200',
    imageHeight: '630',
    url: `${SITE_ORIGIN}/jobs/${encodeURIComponent(slug)}`,
    twitterCard: 'summary_large_image',
  });
}

async function fetchContentOg(type, slug) {
  const res = await fetch(
    `${ATLANTIUM_API_BASE}/content/documents/${type}/${encodeURIComponent(slug)}`
  );
  if (!res.ok) return null;

  const { document: doc, json_ld: jsonLd } = await res.json();
  if (!doc || !doc.title) return null;

  const surface = type === 'post' ? 'blog' : 'docs';
  const canonical = `${SITE_ORIGIN}/${surface}/${encodeURIComponent(doc.slug)}`;
  const description = (doc.excerpt ||
    `${doc.title} — on the Atlantium ${type === 'post' ? 'blog' : 'docs'}.`).slice(0, 250);

  // Canonical + JSON-LD ride the `extra` slot; crawlers get exactly what
  // anonymous users get (the preview IS the indexable content — no cloaking).
  const extra = `
    <link rel="canonical" href="${escapeHtml(canonical)}" />
    ${jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>` : ''}`;

  return buildOgString({
    type: 'article',
    siteName: 'Atlantium',
    title: `${doc.title} — Atlantium`,
    description,
    image: doc.cover_image_url || `${SITE_ORIGIN}/logo-og.png`,
    url: canonical,
    twitterCard: doc.cover_image_url ? 'summary_large_image' : 'summary',
    extra,
  });
}

async function fetchDirectoryOg(kind, slug) {
  const res = await fetch(`${ATLANTIUM_API_BASE}/directory/${kind}/${encodeURIComponent(slug)}`);
  if (!res.ok) return null;

  const { entry } = await res.json();
  if (!entry || !entry.name) return null;

  const canonical = `${SITE_ORIGIN}/directory/${kind}/${encodeURIComponent(entry.slug)}`;
  const amount = entry.grant && entry.grant.amount_max
    ? `Up to $${Math.round(entry.grant.amount_max / 1000)}k`
    : null;
  const days = entry.grant && typeof entry.grant.days_until_close === 'number'
    ? (entry.grant.days_until_close <= 0 ? 'Closes today' : `${entry.grant.days_until_close} days left`)
    : null;
  const description = [entry.summary, amount, days].filter(Boolean).join(' · ').slice(0, 250);

  // MonetaryGrant structured data — grants are exactly what this type is for.
  const jsonLd = entry.kind === 'grant'
    ? {
        '@context': 'https://schema.org',
        '@type': 'MonetaryGrant',
        name: entry.name,
        description: entry.summary || undefined,
        url: canonical,
        funder: entry.grant && entry.grant.funder
          ? { '@type': 'Organization', name: entry.grant.funder }
          : undefined,
        amount: entry.grant && entry.grant.amount_max
          ? { '@type': 'MonetaryAmount', currency: 'USD', maxValue: entry.grant.amount_max, minValue: entry.grant.amount_min || undefined }
          : undefined,
      }
    : {
        '@context': 'https://schema.org',
        '@type': 'GovernmentService',
        name: entry.name,
        description: entry.summary || undefined,
        url: canonical,
      };

  const extra = `
    <link rel="canonical" href="${escapeHtml(canonical)}" />
    <script type="application/ld+json">${JSON.stringify(jsonLd)}</script>`;

  const kindLabel = entry.kind === 'grant' ? 'Atlanta Grants & Programs'
    : entry.kind === 'investor' ? 'Atlanta Investors'
    : entry.kind === 'company' ? 'Atlanta Companies Hiring'
    : 'Atlanta Programs';

  return buildOgString({
    type: 'website',
    siteName: 'Atlantium',
    title: `${entry.name} — ${kindLabel}`,
    description: description || `${entry.name} — on the Atlantium directory.`,
    image: `${SITE_ORIGIN}/og/directory/${kind}/${encodeURIComponent(entry.slug)}.png?v=${OG_RENDER_VERSION}`,
    imageWidth: '1200',
    imageHeight: '630',
    url: canonical,
    twitterCard: 'summary_large_image',
    extra,
  });
}


// ---------------------------------------------------------------------------
// Directory OG cards — grants, programs, investors, companies
// ---------------------------------------------------------------------------

async function renderDirectoryOgImage(kind, slug, request) {
  const cache = caches.default;
  const cacheUrl = new URL(request.url);
  cacheUrl.searchParams.set('v', OG_RENDER_VERSION);
  const cacheKey = new Request(cacheUrl.toString(), { method: 'GET' });
  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  const res = await fetch(`${ATLANTIUM_API_BASE}/directory/${kind}/${encodeURIComponent(slug)}`);
  if (!res.ok) return Response.redirect(`${SITE_ORIGIN}/og-image.png`, 302);
  const { entry, jobs } = await res.json();
  if (!entry || !entry.name) return Response.redirect(`${SITE_ORIGIN}/og-image.png`, 302);

  const THEME = {
    grant:    { label: 'ATLANTA GRANTS',    accent: '#22d3ee', glow: 'rgba(14,165,233,0.16)' },
    resource: { label: 'ATLANTA PROGRAMS',  accent: '#a78bfa', glow: 'rgba(139,92,246,0.16)' },
    investor: { label: 'ATLANTA INVESTORS', accent: '#34d399', glow: 'rgba(16,185,129,0.16)' },
    company:  { label: 'HIRING IN ATLANTA', accent: '#7dd3fc', glow: 'rgba(56,189,248,0.16)' },
  }[kind] || { label: 'ATLANTIUM DIRECTORY', accent: '#22d3ee', glow: 'rgba(14,165,233,0.16)' };

  const badge = (label, color, bg, border) => `
    <div style="display: flex; align-items: center; margin-right: 14px; padding: 6px 16px; border-radius: 999px; font-size: 22px; font-weight: 600; color: ${color}; background: ${bg}; border: 1px solid ${border};">${escapeCard(label)}</div>`;

  const g = entry.grant || {};
  const amount = g.amount_max
    ? (g.amount_min ? `$${Math.round(g.amount_min / 1000)}k\u2013$${Math.round(g.amount_max / 1000)}k` : `Up to $${Math.round(g.amount_max / 1000)}k`)
    : null;
  const days = typeof g.days_until_close === 'number'
    ? (g.days_until_close <= 0 ? 'Closes today' : `${g.days_until_close} days left`)
    : (g.recurring ? 'Rolling deadline' : null);

  const badges = [
    amount ? badge(amount, '#6ee7b7', 'rgba(16,185,129,0.10)', 'rgba(16,185,129,0.35)') : '',
    days ? badge(days, '#fcd34d', 'rgba(245,158,11,0.12)', 'rgba(245,158,11,0.4)') : '',
    g.funder ? badge(g.funder.length > 32 ? `${g.funder.slice(0, 30)}\u2026` : g.funder, '#a5b4fc', 'rgba(99,102,241,0.12)', 'rgba(99,102,241,0.4)') : '',
    entry.resource && entry.resource.category ? badge(entry.resource.category.replace(/_/g, ' '), '#c4b5fd', 'rgba(139,92,246,0.12)', 'rgba(139,92,246,0.4)') : '',
    kind === 'company' && jobs && jobs.length ? badge(`${jobs.length} open role${jobs.length === 1 ? '' : 's'}`, '#34d399', 'rgba(16,185,129,0.12)', 'rgba(16,185,129,0.4)') : '',
  ].filter(Boolean).join('');

  const name = entry.name.length > 60 ? `${entry.name.slice(0, 57)}\u2026` : entry.name;
  const summary = entry.summary
    ? (entry.summary.length > 150 ? `${entry.summary.slice(0, 147)}\u2026` : entry.summary)
    : '';
  let location = (entry.location || 'Atlanta, GA').split(/\s+or\s+/i)[0];
  if (location.length > 30) location = `${location.slice(0, 28)}\u2026`;

  const cta = kind === 'grant' ? 'View deadline & eligibility'
    : kind === 'company' ? 'See open roles'
    : kind === 'investor' ? 'View investor profile'
    : 'View program';

  const html = `
  <div style="display: flex; flex-direction: column; width: 1200px; height: 630px; background: linear-gradient(135deg, #04070d 0%, #071120 55%, #0a1a2e 100%); padding: 56px 64px; font-family: 'Inter'; position: relative;">
    <div style="display: flex; position: absolute; top: -180px; right: -140px; width: 520px; height: 520px; border-radius: 999px; background: ${THEME.glow};"></div>
    <div style="display: flex; position: absolute; bottom: -220px; left: -160px; width: 480px; height: 480px; border-radius: 999px; background: rgba(99,102,241,0.10);"></div>

    <div style="display: flex; align-items: center; justify-content: space-between;">
      <div style="display: flex; align-items: center; flex-shrink: 0;">
        <div style="display: flex; font-size: 34px; font-weight: 800; color: #ffffff; letter-spacing: 2px;">ATLANTIUM</div>
        <div style="display: flex; flex-shrink: 0; white-space: nowrap; margin-left: 18px; padding: 6px 14px; border-radius: 999px; font-size: 20px; font-weight: 600; color: ${THEME.accent}; background: rgba(6,182,212,0.1); border: 1px solid rgba(6,182,212,0.35); letter-spacing: 1px;">${THEME.label}</div>
      </div>
      <div style="display: flex; margin-left: 24px; font-size: 22px; color: #64748b;">${escapeCard(location)}</div>
    </div>

    <div style="display: flex; flex-direction: column; margin-top: 56px; flex-grow: 1;">
      <div style="display: flex; font-size: ${name.length > 40 ? 54 : 64}px; font-weight: 800; color: #f8fafc; line-height: 1.15; max-width: 1050px;">${escapeCard(name)}</div>
      ${summary ? `<div style="display: flex; margin-top: 20px; font-size: 26px; color: #94a3b8; line-height: 1.35; max-width: 1000px;">${escapeCard(summary)}</div>` : ''}
      <div style="display: flex; margin-top: 28px; flex-wrap: wrap;">${badges}</div>
    </div>

    <div style="display: flex; align-items: center; justify-content: space-between; border-top: 1px solid rgba(148,163,184,0.15); padding-top: 24px;">
      <div style="display: flex; font-size: 22px; color: #94a3b8;">atlantium.ai/directory</div>
      <div style="display: flex; font-size: 22px; font-weight: 600; color: ${THEME.accent};">${escapeCard(cta)}</div>
    </div>
  </div>`;

  const [regular, semibold, extrabold] = await Promise.all([
    loadFont(FONT_URLS.regular),
    loadFont(FONT_URLS.semibold),
    loadFont(FONT_URLS.extrabold),
  ]);

  const image = new ImageResponse(html, {
    width: 1200,
    height: 630,
    fonts: [
      { name: 'Inter', data: regular, weight: 400, style: 'normal' },
      { name: 'Inter', data: semibold, weight: 600, style: 'normal' },
      { name: 'Inter', data: extrabold, weight: 800, style: 'normal' },
    ],
  });

  const response = new Response(image.body, {
    headers: {
      'content-type': 'image/png',
      'cache-control': 'public, max-age=86400, s-maxage=604800',
    },
  });
  await cache.put(cacheKey, response.clone());
  return response;
}

// ---------------------------------------------------------------------------
// Per-job OG image (1200x630 PNG rendered with satori/resvg via workers-og)
// ---------------------------------------------------------------------------

const OG_RENDER_VERSION = '7';

const FONT_URLS = {
  regular: 'https://cdn.jsdelivr.net/fontsource/fonts/inter@latest/latin-400-normal.ttf',
  semibold: 'https://cdn.jsdelivr.net/fontsource/fonts/inter@latest/latin-600-normal.ttf',
  extrabold: 'https://cdn.jsdelivr.net/fontsource/fonts/inter@latest/latin-800-normal.ttf',
};

async function loadFont(url) {
  const req = new Request(url, { cf: { cacheTtl: 604800, cacheEverything: true } });
  const res = await fetch(req);
  if (!res.ok) throw new Error(`font fetch failed: ${url}`);
  return res.arrayBuffer();
}

function formatSalaryRange(min, max) {
  const fmt = (n) => (n >= 1000 ? `$${Math.round(n / 1000)}k` : `$${n}`);
  if (min && max) return `${fmt(min)} – ${fmt(max)}`;
  if (min) return `${fmt(min)}+`;
  if (max) return `Up to ${fmt(max)}`;
  return null;
}

async function renderJobOgImage(slug, request) {
  // Serve from the edge cache when we can.
  const cache = caches.default;
  const cacheUrl = new URL(request.url);
  cacheUrl.searchParams.set('v', OG_RENDER_VERSION);
  const cacheKey = new Request(cacheUrl.toString(), { method: 'GET' });
  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  const res = await fetch(
    `${ATLANTIUM_API_BASE}/job_postings/${encodeURIComponent(slug)}`
  );
  if (!res.ok) return Response.redirect(`${SITE_ORIGIN}/og-image.png`, 302);
  const job = await res.json();
  if (!job || !job.title) return Response.redirect(`${SITE_ORIGIN}/og-image.png`, 302);

  const newDate = job.posted_at || job.created_at;
  const newAge = newDate ? Date.now() - new Date(newDate).getTime() : -1;
  const isNewThisWeek = newAge >= 0 && newAge < 7 * 24 * 60 * 60 * 1000;

  const salary = formatSalaryRange(job.salary_min, job.salary_max);
  const stack = ((job.content && job.content.tech_stack) || []).slice(0, 6);
  let location = (job.location || 'Atlanta, GA').split(',').slice(0, 2).join(',');
  if (location.length > 30) location = `${location.slice(0, 28)}\u2026`;

  const badge = (label, color, bg, border) => `
    <div style="display: flex; align-items: center; margin-right: 14px; padding: 6px 16px; border-radius: 999px; font-size: 22px; font-weight: 600; color: ${color}; background: ${bg}; border: 1px solid ${border};">${escapeCard(label)}</div>`;

  const badges = [
    isNewThisWeek ? badge('New this week', '#22d3ee', 'rgba(6,182,212,0.15)', 'rgba(34,211,238,0.5)') : '',
    job.workplace_type ? badge(job.workplace_type, '#34d399', 'rgba(16,185,129,0.12)', 'rgba(16,185,129,0.4)') : '',
    job.seniority ? badge(job.seniority, '#a5b4fc', 'rgba(99,102,241,0.12)', 'rgba(99,102,241,0.4)') : '',
    salary ? badge(salary, '#6ee7b7', 'rgba(16,185,129,0.08)', 'rgba(16,185,129,0.3)') : '',
  ].filter(Boolean).join('');

  const chips = stack
    .map(
      (t) => `
    <div style="display: flex; margin-right: 10px; margin-bottom: 10px; padding: 5px 14px; border-radius: 8px; font-size: 20px; font-weight: 400; color: #67e8f9; background: rgba(6,182,212,0.1); border: 1px solid rgba(6,182,212,0.25);">${escapeCard(t)}</div>`
    )
    .join('');

  const title = job.title.length > 70 ? `${job.title.slice(0, 67)}…` : job.title;

  const html = `
  <div style="display: flex; flex-direction: column; width: 1200px; height: 630px; background: linear-gradient(135deg, #04070d 0%, #071120 55%, #0a1a2e 100%); padding: 56px 64px; font-family: 'Inter'; position: relative;">
    <div style="display: flex; position: absolute; top: -180px; right: -140px; width: 520px; height: 520px; border-radius: 999px; background: rgba(14,165,233,0.14);"></div>
    <div style="display: flex; position: absolute; bottom: -220px; left: -160px; width: 480px; height: 480px; border-radius: 999px; background: rgba(99,102,241,0.10);"></div>

    <div style="display: flex; align-items: center; justify-content: space-between;">
      <div style="display: flex; align-items: center; flex-shrink: 0;">
        <div style="display: flex; font-size: 34px; font-weight: 800; color: #ffffff; letter-spacing: 2px;">ATLANTIUM</div>
        <div style="display: flex; flex-shrink: 0; white-space: nowrap; margin-left: 18px; padding: 6px 14px; border-radius: 999px; font-size: 20px; font-weight: 600; color: #22d3ee; background: rgba(6,182,212,0.1); border: 1px solid rgba(6,182,212,0.35); letter-spacing: 1px;">ATLANTA TECH JOBS</div>
      </div>
      <div style="display: flex; margin-left: 24px; font-size: 22px; color: #64748b;">${escapeCard(location)}</div>
    </div>

    <div style="display: flex; flex-direction: column; margin-top: 64px; flex-grow: 1;">
      <div style="display: flex; font-size: ${title.length > 40 ? 54 : 64}px; font-weight: 800; color: #f8fafc; line-height: 1.15; max-width: 1050px;">${escapeCard(title)}</div>
      <div style="display: flex; margin-top: 20px; font-size: 32px; font-weight: 600; color: #7dd3fc;">${escapeCard(job.company || '')}</div>
      <div style="display: flex; margin-top: 28px;">${badges}</div>
    </div>

    <div style="display: flex; flex-direction: column;">
      ${chips ? `<div style="display: flex; flex-wrap: wrap; margin-bottom: 26px;">${chips}</div>` : ''}
      <div style="display: flex; align-items: center; justify-content: space-between; border-top: 1px solid rgba(148,163,184,0.15); padding-top: 24px;">
        <div style="display: flex; font-size: 22px; color: #94a3b8;">atlantium.ai/jobs</div>
        <div style="display: flex; font-size: 22px; font-weight: 600; color: #34d399;">Apply now</div>
      </div>
    </div>
  </div>`;

  const [regular, semibold, extrabold] = await Promise.all([
    loadFont(FONT_URLS.regular),
    loadFont(FONT_URLS.semibold),
    loadFont(FONT_URLS.extrabold),
  ]);

  const image = new ImageResponse(html, {
    width: 1200,
    height: 630,
    fonts: [
      { name: 'Inter', data: regular, weight: 400, style: 'normal' },
      { name: 'Inter', data: semibold, weight: 600, style: 'normal' },
      { name: 'Inter', data: extrabold, weight: 800, style: 'normal' },
    ],
  });

  const response = new Response(image.body, {
    headers: {
      'content-type': 'image/png',
      'cache-control': 'public, max-age=86400, s-maxage=86400',
    },
  });
  await cache.put(cacheKey, response.clone());
  return response;
}

/**
 * The /jobs hub card, rendered live. The old static PNG baked in a role count
 * that was wrong within a week; this reads the board's own totals so the
 * unfurl is always true. Falls back to the shipped PNG if the API is down.
 */
async function renderJobsIndexOgImage(request) {
  const cache = caches.default;
  const cacheUrl = new URL(request.url);
  cacheUrl.searchParams.set('v', OG_RENDER_VERSION);
  const cacheKey = new Request(cacheUrl.toString(), { method: 'GET' });
  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  let total = null;
  let newThisWeek = null;
  try {
    const res = await fetch(`${ATLANTIUM_API_BASE}/job_postings?format=paged&limit=1`);
    if (res.ok) {
      const data = await res.json();
      total = typeof data.total === 'number' ? data.total : null;
      newThisWeek = data.counts && typeof data.counts.new_this_week === 'number' ? data.counts.new_this_week : null;
    }
  } catch (_) { /* fall through to the static card */ }
  if (total == null) return Response.redirect(`${SITE_ORIGIN}/og-jobs.png`, 302);

  const roleCount = total.toLocaleString('en-US');
  const freshLine = newThisWeek ? `${newThisWeek.toLocaleString('en-US')} new this week` : 'Updated every 4 hours';

  const html = `
  <div style="display: flex; flex-direction: column; width: 1200px; height: 630px; background: linear-gradient(135deg, #04070d 0%, #071120 55%, #0a1a2e 100%); padding: 64px; font-family: 'Inter'; position: relative;">
    <div style="display: flex; position: absolute; top: -200px; right: -160px; width: 560px; height: 560px; border-radius: 999px; background: rgba(16,185,129,0.13);"></div>
    <div style="display: flex; position: absolute; bottom: -240px; left: -180px; width: 520px; height: 520px; border-radius: 999px; background: rgba(14,165,233,0.10);"></div>

    <div style="display: flex; align-items: center;">
      <div style="display: flex; font-size: 34px; font-weight: 800; color: #ffffff; letter-spacing: 2px;">ATLANTIUM</div>
      <div style="display: flex; flex-shrink: 0; white-space: nowrap; margin-left: 18px; padding: 6px 14px; border-radius: 999px; font-size: 20px; font-weight: 600; color: #34d399; background: rgba(16,185,129,0.1); border: 1px solid rgba(16,185,129,0.35); letter-spacing: 1px;">LIVE</div>
    </div>

    <div style="display: flex; flex-direction: column; margin-top: 72px; flex-grow: 1;">
      <div style="display: flex; font-size: 82px; font-weight: 800; color: #f8fafc; line-height: 1.05;">Realtime ATL</div>
      <div style="display: flex; font-size: 82px; font-weight: 800; color: #f8fafc; line-height: 1.05;">Tech Job Index</div>
      <div style="display: flex; margin-top: 30px; font-size: 30px; font-weight: 600; color: #7dd3fc;">${escapeCard(roleCount)} verified roles · ${escapeCard(freshLine)}</div>
    </div>

    <div style="display: flex; align-items: center; justify-content: space-between; border-top: 1px solid rgba(148,163,184,0.15); padding-top: 26px;">
      <div style="display: flex; font-size: 24px; color: #94a3b8;">atlantium.ai/jobs</div>
      <div style="display: flex; font-size: 24px; font-weight: 600; color: #34d399;">Atlanta's Technology Network</div>
    </div>
  </div>`;

  const [regular, semibold, extrabold] = await Promise.all([
    loadFont(FONT_URLS.regular),
    loadFont(FONT_URLS.semibold),
    loadFont(FONT_URLS.extrabold),
  ]);

  const image = new ImageResponse(html, {
    width: 1200,
    height: 630,
    fonts: [
      { name: 'Inter', data: regular, weight: 400, style: 'normal' },
      { name: 'Inter', data: semibold, weight: 600, style: 'normal' },
      { name: 'Inter', data: extrabold, weight: 800, style: 'normal' },
    ],
  });

  // Short TTL: the card carries a live count, so it should not outlive a
  // sync cycle by much.
  const response = new Response(image.body, {
    headers: {
      'content-type': 'image/png',
      'cache-control': 'public, max-age=3600, s-maxage=3600',
    },
  });
  await cache.put(cacheKey, response.clone());
  return response;
}

/**
 * Square (1080x1080) job card built for posting directly to LinkedIn/IG —
 * not a link unfurl. Text and logo are rendered deterministically rather
 * than generated, because the whole pitch is that these numbers are real:
 * a model that hallucinates one digit of a salary costs more credibility
 * than the card earns.
 */
async function renderSocialJobCard(slug, request) {
  const cache = caches.default;
  const cacheUrl = new URL(request.url);
  cacheUrl.searchParams.set('v', OG_RENDER_VERSION);
  const cacheKey = new Request(cacheUrl.toString(), { method: 'GET' });
  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  const res = await fetch(`${ATLANTIUM_API_BASE}/job_postings/${encodeURIComponent(slug)}`);
  if (!res.ok) return new Response('not found', { status: 404 });
  const job = await res.json();
  if (!job || !job.title) return new Response('not found', { status: 404 });

  const fmtK = (n) => `$${Math.round(n / 1000)}k`;
  const salary = job.salary_max
    ? (job.salary_min ? `${fmtK(job.salary_min)} – ${fmtK(job.salary_max)}` : fmtK(job.salary_max))
    : null;
  // Favicons come back at 64px; ask for 256 so the mark is crisp at card scale.
  const logo = job.company_logo ? job.company_logo.replace(/sz=\d+/, 'sz=256') : null;
  const title = job.title.length > 58 ? `${job.title.slice(0, 55)}…` : job.title;
  const meta = [job.seniority, job.workplace_type].filter(Boolean).join(' · ');
  // Multi-city postings ("Charlotte or Greensboro or Atlanta or …") wrap the
  // card. This is an Atlanta board, so say Atlanta when it is on the list;
  // otherwise take the first city named.
  const rawLoc = String(job.location || '');
  const city = /atlanta/i.test(rawLoc) ? 'Atlanta' : rawLoc.split(/ or |,/)[0].trim();
  // Certification names run long ("Control Objectives for Information and
  // Related Technology (COBIT)"); chips only work when they stay chip-sized.
  const tech = (Array.isArray(job.content?.tech_stack) ? job.content.tech_stack : [])
    .filter((t) => typeof t === 'string' && t.length <= 20)
    .slice(0, 4);

  const chip = (t) => `<div style="display: flex; margin-right: 12px; margin-top: 12px; padding: 10px 20px; border-radius: 999px; font-size: 26px; color: #7dd3fc; background: rgba(6,182,212,0.10); border: 1px solid rgba(6,182,212,0.30);">${escapeCard(t)}</div>`;

  // Generated plate (Atlas Cloud) behind a two-stop scrim: the art carries the
  // attention, the scrim guarantees the numbers stay readable. `bg=skyline`
  // swaps to the aerial photograph.
  const bgFile = new URL(request.url).searchParams.get('bg') === 'skyline' ? 'card-bg-skyline.jpg' : 'card-bg.jpg';
  const html = `
  <div style="display: flex; flex-direction: column; width: 1080px; height: 1080px; background: #04070d; padding: 72px; font-family: 'Inter'; position: relative;">
    <img src="${SITE_ORIGIN}/${bgFile}" width="1080" height="1080" style="position: absolute; top: 0; left: 0;" />
    <div style="display: flex; position: absolute; top: 0; left: 0; width: 1080px; height: 1080px; background: linear-gradient(105deg, rgba(4,7,13,0.95) 0%, rgba(4,7,13,0.88) 42%, rgba(4,7,13,0.55) 72%, rgba(4,7,13,0.35) 100%);"></div>
    <div style="display: flex; position: absolute; top: 0; left: 0; width: 1080px; height: 1080px; background: linear-gradient(180deg, rgba(4,7,13,0.75) 0%, rgba(4,7,13,0.15) 35%, rgba(4,7,13,0.55) 82%, rgba(4,7,13,0.92) 100%);"></div>

    <div style="display: flex; align-items: center;">
      <div style="display: flex; font-size: 30px; font-weight: 800; color: #ffffff; letter-spacing: 3px;">ATLANTIUM</div>
      <div style="display: flex; margin-left: 16px; padding: 6px 16px; border-radius: 999px; font-size: 20px; font-weight: 600; color: #34d399; background: rgba(16,185,129,0.10); border: 1px solid rgba(16,185,129,0.35); letter-spacing: 1px;">HIRING NOW</div>
    </div>

    <div style="display: flex; flex-direction: column; margin-top: 88px; flex-grow: 1;">
      ${salary ? `<div style="display: flex; font-size: 92px; font-weight: 800; color: #34d399; line-height: 1;">${escapeCard(salary)}</div>` : ''}
      <div style="display: flex; margin-top: ${salary ? 40 : 0}px; font-size: ${title.length > 34 ? 54 : 64}px; font-weight: 800; color: #f8fafc; line-height: 1.15;">${escapeCard(title)}</div>
      <div style="display: flex; align-items: center; margin-top: 34px;">
        ${logo ? `<img src="${escapeCard(logo)}" width="60" height="60" style="border-radius: 12px;" />` : ''}
        <div style="display: flex; margin-left: ${logo ? 20 : 0}px; font-size: 40px; font-weight: 600; color: #e2e8f0;">${escapeCard(job.company || '')}</div>
      </div>
      ${meta ? `<div style="display: flex; margin-top: 22px; font-size: 30px; color: #94a3b8;">${escapeCard(meta)}${city ? ` · ${escapeCard(city)}` : ''}</div>` : ''}
      ${tech.length ? `<div style="display: flex; flex-wrap: wrap; margin-top: 24px;">${tech.map(chip).join('')}</div>` : ''}
    </div>

    <div style="display: flex; align-items: center; justify-content: space-between; border-top: 1px solid rgba(148,163,184,0.15); padding-top: 32px;">
      <div style="display: flex; font-size: 28px; color: #94a3b8;">atlantium.ai/jobs</div>
      <div style="display: flex; font-size: 28px; font-weight: 600; color: #34d399;">Atlanta's Technology Network</div>
    </div>
  </div>`;

  const [regular, semibold, extrabold] = await Promise.all([
    loadFont(FONT_URLS.regular),
    loadFont(FONT_URLS.semibold),
    loadFont(FONT_URLS.extrabold),
  ]);

  const image = new ImageResponse(html, {
    width: 1080,
    height: 1080,
    fonts: [
      { name: 'Inter', data: regular, weight: 400, style: 'normal' },
      { name: 'Inter', data: semibold, weight: 600, style: 'normal' },
      { name: 'Inter', data: extrabold, weight: 800, style: 'normal' },
    ],
  });
  const response = new Response(image.body, {
    headers: { 'content-type': 'image/png', 'cache-control': 'public, max-age=86400' },
  });
  await cache.put(cacheKey, response.clone());
  return response;
}

/**
 * Carousel cover slide (1080x1080). The first frame has one job: stop the
 * scroll and promise what is behind it. Live counts, so the hook is never a
 * stale claim, plus an explicit swipe affordance — Threads and LinkedIn both
 * bury the "1/11" indicator, and a carousel nobody swipes is a single post.
 */
async function renderCarouselCover(request) {
  const url = new URL(request.url);
  const count = url.searchParams.get('count') || '10';
  const cache = caches.default;
  const cacheUrl = new URL(request.url);
  cacheUrl.searchParams.set('v', OG_RENDER_VERSION);
  const cacheKey = new Request(cacheUrl.toString(), { method: 'GET' });
  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  let total = null, over200 = null, week = null;
  try {
    const res = await fetch(`${ATLANTIUM_API_BASE}/job_postings?format=paged&limit=1`);
    if (res.ok) {
      const d = await res.json();
      total = typeof d.total === 'number' ? d.total : null;
      week = d.counts?.new_this_week ?? null;
    }
    const ins = await fetch(`${ATLANTIUM_API_BASE}/job_postings/insights`);
    if (ins.ok) {
      const d = await ins.json();
      const bands = d.salary_bands || [];
      over200 = bands.filter((b) => b.bucket >= 9).reduce((a, b) => a + b.n, 0);
    }
  } catch (_) { /* render without the stat row */ }

  const stat = (v, l) => `
    <div style="display: flex; flex-direction: column; margin-right: 56px;">
      <div style="display: flex; font-size: 46px; font-weight: 800; color: #34d399;">${escapeCard(v)}</div>
      <div style="display: flex; font-size: 21px; color: #94a3b8; letter-spacing: 1px;">${escapeCard(l)}</div>
    </div>`;

  const html = `
  <div style="display: flex; flex-direction: column; width: 1080px; height: 1080px; background: linear-gradient(140deg, #04070d 0%, #071120 55%, #0a1a2e 100%); padding: 72px; font-family: 'Inter'; position: relative;">
    <div style="display: flex; position: absolute; top: -240px; right: -200px; width: 680px; height: 680px; border-radius: 999px; background: rgba(16,185,129,0.14);"></div>
    <div style="display: flex; position: absolute; bottom: -280px; left: -220px; width: 600px; height: 600px; border-radius: 999px; background: rgba(14,165,233,0.11);"></div>

    <div style="display: flex; align-items: center;">
      <div style="display: flex; font-size: 30px; font-weight: 800; color: #ffffff; letter-spacing: 3px;">ATLANTIUM</div>
      <div style="display: flex; margin-left: 16px; padding: 6px 16px; border-radius: 999px; font-size: 20px; font-weight: 600; color: #34d399; background: rgba(16,185,129,0.10); border: 1px solid rgba(16,185,129,0.35); letter-spacing: 1px;">LIVE</div>
    </div>

    <div style="display: flex; flex-direction: column; margin-top: 76px; flex-grow: 1;">
      <div style="display: flex; font-size: 26px; font-weight: 600; color: #7dd3fc; letter-spacing: 3px;">THIS WEEK IN ATLANTA</div>
      <div style="display: flex; margin-top: 26px; font-size: 104px; font-weight: 800; color: #f8fafc; line-height: 0.98;">The ${escapeCard(count)}</div>
      <div style="display: flex; font-size: 104px; font-weight: 800; color: #f8fafc; line-height: 0.98;">highest-paying</div>
      <div style="display: flex; font-size: 104px; font-weight: 800; color: #34d399; line-height: 0.98;">tech jobs</div>
      ${total != null ? `<div style="display: flex; margin-top: 56px;">
        ${stat(total.toLocaleString('en-US'), 'ROLES INDEXED')}
        ${over200 != null ? stat(String(over200), 'PAY $200K+') : ''}
        ${week != null ? stat(week.toLocaleString('en-US'), 'NEW THIS WEEK') : ''}
      </div>` : ''}
    </div>

    <div style="display: flex; align-items: center; justify-content: space-between; border-top: 1px solid rgba(148,163,184,0.15); padding-top: 32px;">
      <div style="display: flex; font-size: 28px; color: #94a3b8;">atlantium.ai/jobs</div>
      <div style="display: flex; align-items: center;">
        <div style="display: flex; font-size: 26px; font-weight: 700; color: #34d399; letter-spacing: 3px; margin-right: 18px;">SWIPE</div>
        <div style="display: flex; align-items: center; justify-content: center; width: 62px; height: 62px; border-radius: 999px; background: rgba(16,185,129,0.14); border: 2px solid rgba(52,211,153,0.55);">
          <img width="30" height="30" src="data:image/svg+xml;utf8,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="#34d399" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h13M12 5l7 7-7 7"/></svg>')}" />
        </div>
      </div>
    </div>
  </div>`;

  const [regular, semibold, extrabold] = await Promise.all([
    loadFont(FONT_URLS.regular),
    loadFont(FONT_URLS.semibold),
    loadFont(FONT_URLS.extrabold),
  ]);
  const image = new ImageResponse(html, {
    width: 1080,
    height: 1080,
    fonts: [
      { name: 'Inter', data: regular, weight: 400, style: 'normal' },
      { name: 'Inter', data: semibold, weight: 600, style: 'normal' },
      { name: 'Inter', data: extrabold, weight: 800, style: 'normal' },
    ],
  });
  const response = new Response(image.body, {
    headers: { 'content-type': 'image/png', 'cache-control': 'public, max-age=1800' },
  });
  await cache.put(cacheKey, response.clone());
  return response;
}

function staticHubOg({ title, description, path, image = 'og-image.png' }) {
  return buildOgString({
    type: 'website',
    siteName: 'Atlantium',
    title,
    description,
    image: `${SITE_ORIGIN}/${image}`,
    url: `${SITE_ORIGIN}${path}`,
    twitterCard: 'summary_large_image',
  });
}

function staticFocusGroupsOg() {
  return buildOgString({
    type: 'website',
    siteName: 'Atlantium',
    title: 'Focus Groups — AI-Powered Collaboration Cohorts | Atlantium',
    description:
      'Join 2-week intensive collaborations with AI-matched members. Build meaningful connections, learn from expert leads, and ship together.',
    image: `${SITE_ORIGIN}/og-focus-groups.png`,
    url: `${SITE_ORIGIN}/focus-groups`,
    twitterCard: 'summary_large_image',
  });
}

// ---------------------------------------------------------------------------
// Shared utilities
// ---------------------------------------------------------------------------

function buildOgString({ type, siteName, title, description, image, imageWidth, imageHeight, url, twitterCard, extra }) {
  return `
    <!-- Dynamic OG Tags - Injected by Cloudflare Worker -->
    <meta property="og:type" content="${escapeHtml(type)}" />
    <meta property="og:site_name" content="${escapeHtml(siteName)}" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:image" content="${escapeHtml(image)}" />
    ${imageWidth ? `<meta property="og:image:width" content="${escapeHtml(imageWidth)}" />` : ''}
    ${imageHeight ? `<meta property="og:image:height" content="${escapeHtml(imageHeight)}" />` : ''}
    <meta property="og:url" content="${escapeHtml(url)}" />
    ${extra || ''}
    <meta name="twitter:card" content="${escapeHtml(twitterCard)}" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${escapeHtml(image)}" />
    <meta name="description" content="${escapeHtml(description)}" />
    <title>${escapeHtml(title)}</title>
    <!-- End Dynamic OG Tags -->`;
}

function injectOgTags(html, ogTags) {
  html = html
    .replace(/<meta property="og:[^"]*"[^>]*>/gi, '')
    .replace(/<meta property="article:[^"]*"[^>]*>/gi, '')
    .replace(/<meta name="twitter:[^"]*"[^>]*>/gi, '')
    .replace(/<meta name="description"[^>]*>/gi, '')
    .replace(/<title>[^<]*<\/title>/i, '');

  return html.replace(/<head>/i, `<head>${ogTags}`);
}

function escapeCard(str) {
  if (!str) return '';
  return String(str).replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
